name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t abhialgotech/exam_frontend_v1_dev .

      - name: Publish Image to Docker Hub
        run: docker push abhialgotech/exam_frontend_v1_dev:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull abhialgotech/exam_frontend_v1_dev:latest
      - name: Stop Old Container
        run: docker stop exam-react-app-dev || true # Allow continuation if the container doesn't exist
      - name: Delete Old Container
        run: docker rm -f exam-react-app-dev || true # Allow continuation if the container doesn't exist

      - name: Run Docker Container
        run: docker run -d -p 3088:80 --name exam-react-app-dev abhialgotech/exam_frontend_v1_dev
